/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package factura;

/**
 * 
 * @author Edison
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CantP3 = new javax.swing.JTextField();
        NomP3 = new javax.swing.JTextField();
        ValP3 = new javax.swing.JTextField();
        TotP3 = new javax.swing.JTextField();
        TotP2 = new javax.swing.JTextField();
        ValP2 = new javax.swing.JTextField();
        NomP2 = new javax.swing.JTextField();
        CantP2 = new javax.swing.JTextField();
        TotP1 = new javax.swing.JTextField();
        ValP1 = new javax.swing.JTextField();
        NomP1 = new javax.swing.JTextField();
        CantP1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtSubTotal = new javax.swing.JTextField();
        TxtIVA = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtDescuento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        TxtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDescuento1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        NomCliente = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        DirecClien1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        CorreoClien1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CantP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantP3ActionPerformed(evt);
            }
        });
        jPanel1.add(CantP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 50, -1));

        NomP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomP3ActionPerformed(evt);
            }
        });
        jPanel1.add(NomP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 350, -1));

        ValP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValP3ActionPerformed(evt);
            }
        });
        jPanel1.add(ValP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 80, -1));
        jPanel1.add(TotP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 110, -1));
        jPanel1.add(TotP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 110, -1));

        ValP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValP2ActionPerformed(evt);
            }
        });
        jPanel1.add(ValP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 80, -1));
        jPanel1.add(NomP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 350, -1));

        CantP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantP2ActionPerformed(evt);
            }
        });
        jPanel1.add(CantP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 50, -1));

        TotP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotP1ActionPerformed(evt);
            }
        });
        jPanel1.add(TotP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 110, 20));

        ValP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValP1ActionPerformed(evt);
            }
        });
        jPanel1.add(ValP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 80, -1));

        NomP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomP1ActionPerformed(evt);
            }
        });
        jPanel1.add(NomP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 350, 20));
        jPanel1.add(CantP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 50, -1));

        jLabel5.setText("Sub Total:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 100, 20));

        jLabel6.setText("IVA 12%:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 100, 20));
        jPanel1.add(TxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 110, -1));
        jPanel1.add(TxtIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 110, 30));

        jLabel7.setText("Descuento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 80, 20));

        TxtDescuento.setText("0");
        jPanel1.add(TxtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, 110, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, -1, -1));

        TxtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtTotal.setForeground(new java.awt.Color(0, 0, 153));
        TxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalActionPerformed(evt);
            }
        });
        jPanel1.add(TxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 660, 110, 30));

        jLabel10.setText("Total :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, 100, 30));

        jLabel11.setText("Valor descontado: $");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 100, 20));

        txtDescuento1.setText("-");
        jPanel1.add(txtDescuento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 110, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 170, 0));

        jLabel12.setFont(new java.awt.Font("Artifakt Element", 0, 10)); // NOI18N
        jLabel12.setText("Asesores TIC");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Artifakt Element", 0, 10)); // NOI18N
        jLabel13.setText("NIT: 254581112");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, -1, -1));

        jLabel15.setFont(new java.awt.Font("Artifakt Element", 1, 12)); // NOI18N
        jLabel15.setText("Factura Electronica");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, -1));

        jLabel16.setFont(new java.awt.Font("Artifakt Element", 0, 10)); // NOI18N
        jLabel16.setText("Serie: 6C4F9000F");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, -1, 20));

        jLabel17.setFont(new java.awt.Font("Artifakt Element", 0, 10)); // NOI18N
        jLabel17.setText("No:                    ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 60, -1, -1));

        jLabel18.setFont(new java.awt.Font("Artifakt Element", 0, 10)); // NOI18N
        jLabel18.setText("Fecha: 15/06/2022");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 80, -1, -1));

        jLabel19.setFont(new java.awt.Font("Artifakt Element", 1, 10)); // NOI18N
        jLabel19.setText("Documento Tributario Electronico");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edison\\Downloads\\Factura\\Factura\\src\\Imagenes\\Captura de pantalla 2022-06-14 173233.png")); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, -1, 180));

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Edison\\Downloads\\Factura\\Factura\\src\\Imagenes\\Captura de pantalla 2022-06-14 215951.png")); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 600, -1, 90));

        jLabel8.setFont(new java.awt.Font("Artifakt Element", 1, 36)); // NOI18N
        jLabel8.setText("Innovation Company");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1040, 10));

        jLabel14.setFont(new java.awt.Font("Artifakt Element", 1, 12)); // NOI18N
        jLabel14.setText("Nombre: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        NomCliente.setFont(new java.awt.Font("Artifakt Element", 0, 12)); // NOI18N
        jPanel1.add(NomCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 380, -1));

        jLabel22.setFont(new java.awt.Font("Artifakt Element", 1, 12)); // NOI18N
        jLabel22.setText("Direccion: ");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        DirecClien1.setFont(new java.awt.Font("Artifakt Element", 0, 12)); // NOI18N
        jPanel1.add(DirecClien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 380, -1));

        jLabel23.setFont(new java.awt.Font("Artifakt Element", 1, 12)); // NOI18N
        jLabel23.setText("Correo Electronico: ");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        CorreoClien1.setFont(new java.awt.Font("Artifakt Element", 0, 12)); // NOI18N
        CorreoClien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoClien1ActionPerformed(evt);
            }
        });
        jPanel1.add(CorreoClien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 290, 20));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setText("Cantidad");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Valor unitario");

        jLabel4.setText("Importe");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1)
                .addGap(191, 191, 191)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 1020, 40));

        jLabel24.setFont(new java.awt.Font("Artifakt Element", 1, 12)); // NOI18N
        jLabel24.setText("R.U.C / C.I : ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, -1, -1));

        jTextField1.setFont(new java.awt.Font("Artifakt Element", 0, 12)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 290, -1));

        jPanel3.setBackground(new java.awt.Color(253, 233, 197));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        jLabel25.setFont(new java.awt.Font("Artifakt Element", 1, 12)); // NOI18N
        jLabel25.setText("Encargado: ");

        jLabel26.setFont(new java.awt.Font("Artifakt Element", 1, 12)); // NOI18N
        jLabel26.setText("Telefono Movil :");

        jLabel27.setFont(new java.awt.Font("Artifakt Element", 1, 12)); // NOI18N
        jLabel27.setText("Fecha Emision :");

        jTextField2.setFont(new java.awt.Font("Artifakt Element", 0, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jTextField3))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 330, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String cant1 = CantP1.getText();
        String cant2 = CantP2.getText();
        String cant3 = CantP3.getText();
        
        String v1 = ValP1.getText();
        String v2 = ValP2.getText();
        String v3 = ValP3.getText();
        
        int imp1 = Integer.parseInt(cant1) * Integer.parseInt(v1);
        int imp2 = Integer.parseInt(cant2) * Integer.parseInt(v2);
        int imp3 = Integer.parseInt(cant3) * Integer.parseInt(v3);
        
        int sub = imp1 + imp2 + imp3;
        
        double IVA12 = sub * 0.12;
        
        double desc = Double.parseDouble(TxtDescuento.getText());
        double descTotal = (sub * desc / 100);
        double TotalPagar = sub - descTotal + IVA12;
        txtDescuento1.setText(""+descTotal);
        TotP1.setText(""+imp1);
        TotP2.setText(""+imp2);
        TotP3.setText(""+imp3);
        
        TxtSubTotal.setText(""+sub);
        TxtIVA.setText(""+IVA12);
        TxtTotal.setText(""+TotalPagar);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NomP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomP3ActionPerformed

    private void NomP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomP1ActionPerformed

    private void TotP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotP1ActionPerformed

    private void TxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalActionPerformed

    private void CantP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantP3ActionPerformed

    private void ValP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValP3ActionPerformed

    private void CorreoClien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoClien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoClien1ActionPerformed

    private void CantP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantP2ActionPerformed

    private void ValP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValP2ActionPerformed

    private void ValP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValP1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantP1;
    private javax.swing.JTextField CantP2;
    private javax.swing.JTextField CantP3;
    private javax.swing.JTextField CorreoClien1;
    private javax.swing.JTextField DirecClien1;
    private javax.swing.JTextField NomCliente;
    private javax.swing.JTextField NomP1;
    private javax.swing.JTextField NomP2;
    private javax.swing.JTextField NomP3;
    private javax.swing.JTextField TotP1;
    private javax.swing.JTextField TotP2;
    private javax.swing.JTextField TotP3;
    private javax.swing.JTextField TxtDescuento;
    private javax.swing.JTextField TxtIVA;
    private javax.swing.JTextField TxtSubTotal;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JTextField ValP1;
    private javax.swing.JTextField ValP2;
    private javax.swing.JTextField ValP3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel txtDescuento1;
    // End of variables declaration//GEN-END:variables
}
